# Organizations

Organizations:

  - &OrdererOrg
    Name: OrderingService
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/aperam.com/msp
    
    Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"
  - &Gnk
    Name: GnkMSP
    ID: GnkMSP
    MSPDir: crypto-config/peerOrganizations/gnk.aperam.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('GnkMSP.admin', 'GnkMSP.peer', 'GnkMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('GnkMSP.admin', 'GnkMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('GnkMSP.admin')" 
    
    AnchorPeers:
      - Host: peer0.gnk.aperam.com
        Port: 7051

  - &Copr
    Name: CorpMSP
    ID: CorpMSP
    MSPDir: crypto-config/peerOrganizations/corp.aperam.com/msp
    Policies:
          Readers:
              Type: Signature
              Rule: "OR('CorpMSP.admin', 'CorpMSP.peer', 'CorpMSP.client')"
          Writers:
              Type: Signature
              Rule: "OR('CorpMSP.admin', 'CorpMSP.client')"
          Admins:
              Type: Signature
              Rule: "OR('CorpMSP.admin')" 
    AnchorPeers:
      - Host: peer0.corp.aperam.com
        Port: 7051

Capabilities:

    Channel: &ChannelCapabilities

        V1_4_3: true

        V1_3: false

        V1_1: false


    Orderer: &OrdererCapabilities
    
        V1_4_2: true
        V1_1: false

    Application: &ApplicationCapabilities

        V1_4_2: true

        V1_3: false

        V1_2: false

        V1_1: false
# Orderer

Orderer: &OrdererDefaults

  OrdererType: solo
  Addresses: 
    - orderer.aperam.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Kafka:
    Brokers: 
      - 127.0.0.1:9092

  Organizations:
  Policies:
    Readers:
        Type: ImplicitMeta
        Rule: "ANY Readers"
    Writers:
        Type: ImplicitMeta
        Rule: "ANY Writers"
    Admins:
        Type: ImplicitMeta
        Rule: "MAJORITY Admins"
    BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
Channel: &ChannelDefaults

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"


    Capabilities:
        <<: *ChannelCapabilities
# Application

Application: &ApplicationDefaults

  Organizations:
  Policies:
      Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
      Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
      Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"



Profiles:
    OrdererGenesis:
      Capabilities:
        <<: *ChannelCapabilities
      Orderer:
        <<: *OrdererDefaults
        Organizations:
          - *OrdererOrg
        Capabilities:
          <<: *OrdererCapabilities
      Consortiums:
        MyFirstConsortium:
          Organizations:
            - *Gnk 
            - *Corp
            
    aperamChannel:
      Consortium: MyFirstConsortium
      Application:
        <<: *ApplicationDefaults
        Organizations:
          - *Gnk
          - *Corp
          
        Capabilities:
          <<: *ApplicationCapabilities