version: '2'

services:

  orderer.aperam.com:
    container_name: orderer.aperam.com
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/opt/gopath/fabric-samples/aperam/channel-artifacts/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/opt/gopath/fabric-samples/aperam/channel-artifacts/genesis.block
    - ../crypto-config/ordererOrganizations/aperam.com/orderers/orderer.aperam.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/aperam.com/orderers/orderer.aperam.com/tls/:/var/hyperledger/orderer/tls
    - orderer.aperam.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.gnk.aperam.com:
    container_name: peer0.gnk.aperam.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.gnk.aperam.com
      - CORE_PEER_ADDRESS=peer0.gnk.aperam.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.gnk.aperam.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.gnk.aperam.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.gnk.aperam.com:7051
      - CORE_PEER_LOCALMSPID=GnkMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/gnk.aperam.com/peers/peer0.gnk.aperam.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/gnk.aperam.com/peers/peer0.gnk.aperam.com/tls:/etc/hyperledger/fabric/tls
        - peer0.gnk.aperam.com:/var/hyperledger/production
    ports:
      - 7051:7051
  

  peer0.corp.aperam.com:
    container_name: peer0.corp.aperam.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - GODEBUG=netdns=go
      - CORE_PEER_ID=peer0.corp.aperam.com
      - CORE_PEER_ADDRESS=peer0.corp.aperam.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.corp.aperam.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.corp.aperam.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.corp.aperam.com:9051
      - CORE_PEER_LOCALMSPID=CorpMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/corp.aperam.com/peers/peer0.corp.aperam.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/corp.aperam.com/peers/peer0.corp.aperam.com/tls:/etc/hyperledger/fabric/tls
        - peer0.corp.aperam.com:/var/hyperledger/production
    ports:
      - 9051:9051